### ISSUE TITLE
Number of columns in pv2 dataframe?

### ISSUE THREAD

**Issue by merrickj** [mlahariya/EV-SDG#1]
I was trying out this repository, thank you for sharing it.

When running the preprocess script with some session data I have, I have been running into an error at the following line:
`pv2.columns = ['Charge_point','C0','C1','C2']`
of
(https://github.com/mlahariya/EV-SDG/blob/master/preprocess/clustering/pole_clusters.py)

pv2 is a 2 column dataframe for me, as it enters the line of code above. Might there be a bug or is it simply the case that something has gone wrong upstream of this point for me?

**Comment by mlahariya** [comment]
Hey, 

`pv2.columns = ['Charge_point','C0','C1','C2']` 
Line 55 in https://github.com/mlahariya/EV-SDG/blob/master/preprocess/clustering/pole_clusters.py:

Renames the column names of the data frame pv2. This data frame has the pole clusters, given in one-hot encoding for clusters C0, C1, and C3. If pv2 is a 2 column data frame as it enters this line: there was only 1 cluster that was identified, thus two columns ('Charge_point', 'C0'). 

You can solve this in 2 ways:
1) Use only 1 pole cluster - you will need to make changes in the downstream code after this line. 
2) Modify the DBSCAN clustering upstream of this line - to forcefully identify 3 clusters. 

Hope this helps.
